### ISSUE TITLE
Missing tag byte when encoding Sign1 

### ISSUE THREAD

**Issue by mikekelly** [authlete/cbor#6]
Thanks for open sourcing this library, it's good stuff.

Is it intentional that calling `.encode` on a Sign1 message returns a byte array without the required 0xd2 byte tag at the start? If so, I'm curious to understand why it's designed that way :)

Thanks again!

**Comment by TakahikoKawasaki** [comment]
@mikekelly The issue may be because I overlooked the specifications. Could you please quote the relevant section of the specifications?

**Comment by mikekelly** [comment]
https://datatracker.ietf.org/doc/html/rfc8152#section-4.2

```
   The structure can be encoded as either tagged or untagged depending
   on the context it will be used in.  A tagged COSE_Sign1 structure is
   identified by the CBOR tag 18.  The CDDL fragment that represents
   this is:
```

most implementations add this byte by default, I suppose to ensure that the message is fully self-describing.

**Comment by TakahikoKawasaki** [comment]
Thank you. That is, the leading `0xD2` (Tag 18) is NOT mandatory.

`COSESign1.encode()` should not prepend the tag. If a developer needs the tag, `CBORTaggedItem` should be used explicitly.

If `COSESign1.encode()` prepended the tag automatically, a mechanism to prevent the automatic tagging would be needed for cases where the tag should not be used.

Building blocks should not do automatic tagging. Such tagging should be handled in the application layer, not in the library layer. I know the tag (cf. [COSEMessageTagProcessor.java](https://github.com/authlete/cbor/blob/main/src/main/java/com/authlete/cose/COSEMessageTagProcessor.java)), but I don't let `COSESign1.encode()` prepend the tag. This is intentional.

**Comment by mikekelly** [comment]
Ok, this is different than the default behaviour of most Sign1 encoders so
the behaviour was surprising to me. Most decoders require the byte even
though it is optional. I suppose you do save 1 byte by not doing this but I
suspect most applications would not optimise for this. But it’s a design
choice, so fair enough. Thanks for explaining your position

Sent via Superhuman iOS ***@***.***>
